name: Test Packaging

on:
  workflow_dispatch:
  push:
    branches: [ master, 2022.11.07-map-deploy-action ]
    paths:
      - 'Resources/Maps/**.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Setup Submodule
        run: |
          git submodule update --init --recursive

      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5

      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build Map Renderer
        run: |
          dotnet build Content.MapRenderer
      
      - name: Get changed files
        id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          format: 'space-delimited'
